### ISSUE TITLE
Restart after edit toolbar.json

### ISSUE THREAD

**Issue by jerone** [cakecatz/flex-toolbar#1]
Do I need to restart Atom every time I edit the `toolbar.json`? 
If so, is this something that can be worked around?

**Comment by cakecatz** [comment]
@jerone Yeah, need restaring.
And I'll try implementing it on next patch.

**Comment by jerone** [comment]
Closing as fixed in https://github.com/cakecatz/flex-toolbar/commit/f20a3fe34581e72b0863682bb1ade3742a023eea. Thnx!
