### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by madvik** [cakecatz/flex-toolbar#100]
Hi,

Where did you find:
* the atom font-awesome ? On the official website, the code doesn't work.
* the atom callback list ? I don't find it ?

Thanks

**Comment by dodekeract** [comment]
Atom callback list is just Command Shift P. Then just use your best guess and write it in a dashed format.

package-name:toggle etc.

**Comment by madvik** [comment]
Thanks a lot, 
OK, I found for `font-awesome`, I forget `iconset: 'fa'`, and I found : [](https://github.com/suda/tool-bar#supported-icon-sets)
