### ISSUE TITLE
flex-tool-bar is parsing a json file which doesn't exist

### ISSUE THREAD

**Issue by juschu** [cakecatz/flex-toolbar#103]
I get the error "Your toolbar.json is not valid JSON" even if there is only a toolbar.cson in my config folder. And this toolbar.cson works exactly as it should (at least right now). When I save this file I get the message "The tool-bar was successfully updated."
So I added a json file only with {} in it. When I save this file I also get the message "The tool-bar was successfully updated." and the toolbar still shows my buttons.
So it looks like flex-toolbar is first lokking for a cson file. However I still get the message "Your toolbar.json is not valid JSON". It comes out of nowhere and I don't have to save one of those two files to make it apear.

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.
