### ISSUE TITLE
THIS REPO IS NOT ACTIVE

### ISSUE THREAD

**Issue by UziTech** [cakecatz/flex-toolbar#121]
@cakecatz @jerone could one of you respond if this repo is still active otherwise I will try to fork it and merge a couple of the pull requests.

**Comment by jerone** [comment]
I have moved on. You have to talk to @cakecatz if you want to contribute.

**Comment by TJProgrammer** [comment]
Hello! After some research, @cakecatz have two options:
- Transfer the ownership of the repo (more difficult process) or
- Add a new collaborator with high privileges (fast option). 
Now, we have to wait to see what @cakecatz will choose.

**Comment by cakecatz** [comment]
@UziTech Sorry, this repository is not active now

@TJProgrammer Thanks.
I will find collaborator.

**Comment by UziTech** [comment]
@cakecatz I would be willing to help out and be a collaborator

**Comment by cakecatz** [comment]
@UziTech Thank you!!!
I sent invite mail to you.

**Comment by UziTech** [comment]
@cakecatz Thank you. I will still need you too push updates to apm occasionally. Do you just want me to email you when we need an update?

**Comment by cakecatz** [comment]
@UziTech Maybe you can push package update without me.

http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#adding-a-collaborator

> Note: Anyone that has push access to your repository will have the ability to publish new versions of the package that belongs to that repository.

**Comment by UziTech** [comment]
Nice. I did not know that. Thanks

**Comment by TJProgrammer** [comment]
I am glade to see this repo active again!
Thanks.
