### ISSUE TITLE
Add `color` option

### ISSUE THREAD

**Issue by cakecatz** [cakecatz/flex-toolbar#13]
Change button color from toolbar.json.

    {
      "type": "button",
      "icon": "playback-play",
      "callback": "script:run",
      "tooltip": "Run",
      "color": "green"
    }

If you want to set button color to green, you can use `green`, `#00ff00`, `#0f0`.

![screen shot 2015-04-30 at 1 42 24 pm](https://cloud.githubusercontent.com/assets/6136383/7406525/0fb187b6-ef3f-11e4-94db-21be8d2250c7.png)

**Comment by jerone** [comment]
Interesting idea. I guess one can not single out particular buttons to style them by using a custom theme. Just thinking out loud: what about border, background and box-shadow colors?

Probably every [CSS color syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) is allowed:
```
{ "color": "red" }
{ "color": "#f00" }
{ "color": "#ff0000" }
{ "color": "rgb(255,0,0)" }
{ "color": "rgb(100%, 0%, 0%)" }
{ "color": "hsl(0, 100%, 50%)" }
{ "color": "rgba(255, 0, 0, 0.5)" } 
{ "color": "hsla(0, 100%, 50%, 0.5)" }
```

**Comment by cakecatz** [comment]
I think will use inline style.
So can use other properties for buttons.
Or add class to buttons like `toolbar-button-1, toolbar-button-2, ...` and write own stylesheet instead.

**Comment by cakecatz** [comment]
toolbar should have this feature.

**Comment by jerone** [comment]
[**@cakecatz**](https://github.com/cakecatz) commented on [1 mei 2015 17:48 CEST](https://github.com/cakecatz/flex-toolbar/issues/13#issuecomment-98162822 "2015-05-01T15:48:41Z - Replied by Github Comment Enhancer"):
> Or add class to buttons like `toolbar-button-1, toolbar-button-2, ...` and write own stylesheet instead.

I wouldn't use classes, because the order can change. For example with other packages interfering. Inline style is sufficient I guess.

This doesn't seems like a feature Toolbar should have. The toolbar API returns the button that has been added to the bar, for you to extend with properties like jQuery `.css()`.

**Comment by cakecatz** [comment]
@jerone I see, I will use inline style.

> This doesn't seems like a feature Toolbar should have. The toolbar API returns the button that has been added to the bar, for you to extend with properties like jQuery .css().

Okay, that's makes sense.
I've tried using .css() and works fine.
Thank you :relaxed:

**Comment by cakecatz** [comment]
"style": {
      "color": "blue",
      "background": "red"
    }

**Comment by cakecatz** [comment]
Added
210f16b20f2b79661170e8f1a882e05cd92066f9

**Comment by jerone** [comment]
Cool!
This way, any css property is allowed.

_ps. You know you can [close issues within commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/), right... keeps the commits and issues together._
