### ISSUE TITLE
open a folder 

### ISSUE THREAD

**Issue by petKitsune** [cakecatz/flex-toolbar#130]
is there a way to assign a button
to open the OS explorer with a predefined folder
without opening files in Atom

**Comment by UziTech** [comment]
You can use a [function callback](https://github.com/cakecatz/flex-toolbar#function-callback) to open a folder with `child_process` or something like that

**Comment by petKitsune** [comment]
I have already found another way
using Open Unsupported Files
I'm closing this one

and thx for keeping this package going
