### ISSUE TITLE
Package is not compatible with `atom 1.25`

### ISSUE THREAD

**Issue by Greenek** [cakecatz/flex-toolbar#133]
```
Failed to require the main module of 'flex-tool-bar' because it requires one or more incompatible native modules (fsevents).
```

### Solution for beta users

To make `flex-tool-bar` work before patch is delivered, just click `Incompatible Packages` icon (red "bug" icon) in status bar and then select `Rebuild Packages` button.

**Comment by UziTech** [comment]
duplicate of #112

**Comment by UziTech** [comment]
The only real solution to this is for Atom to automatically rebuild packages after updating. I'm not sure if that would create other issues but  the [Atom repo](https://github.com/atom/atom/issues) would be the place to ask for that.
