### ISSUE TITLE
Don't grab values from non-editing panels

### ISSUE THREAD

**Issue by StaticRocket** [cakecatz/flex-toolbar#138]
Suggestion to make it so the toolbar doesn't update from values grabbed from non-editable panels. The grammar indicator in the bottom right doesn't change when you click on non-editable side panels like Tree View or Git Tab so why should the tool-bar? Just a suggestion.

**Comment by UziTech** [comment]
I got something started on #139 

The difficult thing is that flex-toolbar needs to handle things that aren't necessarily text editors (e.g. Images) and I'm not sure how many of those "non-text" editors people are using.

For now it seems to be working but I'm going to test it out for a while before I release it.

**Comment by StaticRocket** [comment]
Right, perhaps one could add a parameter to the buttons to enable or disable this detection method, or make it grammar (or other parameters strictly applying to the text editor section) specific. Push comes to shove you could always make it a toggleable global setting.
