### ISSUE TITLE
A collapse button

### ISSUE THREAD

**Issue by slayerxk** [cakecatz/flex-toolbar#141]
Hey men, i try to do a collapse folder button like the visual code ones, but this callback `tree-view:recursive-collapse-directory` does't works well can you fix that ?

My code:

module.exports = [
	{
		type: 'button',
		icon: 'gear',
		callback: 'flex-tool-bar:edit-config-file',
		tooltip: 'Edit Tool Bar'
	},
	{
		type: 'spacer'
	},
	{
		type: 'button',
		icon: 'angle-left',
		iconset: 'fa',
		callback: [
			"tree-view:toggle-focus",
			

> "tree-view:recursive-collapse-directory"

		],
		tooltip: 'Collapse Folder',
	},
];

**Comment by UziTech** [comment]
Since `tree-view:recursive-collapse-directory` only works when dispatched on the `.tree-view` selector you could do this:

```js
[
	{
		type: "function",
		icon: "angle-left",
		iconset: "fa",
		callback: () => {
			atom.commands.dispatch(
				document.querySelector(".tree-view"),
				"tree-view:recursive-collapse-directory"
			);
		},
		tooltip: "Collapse Folder",
	},
];
```

**Comment by slayerxk** [comment]
it works just when i use in the first time and doesn't works anymore :/

**Comment by UziTech** [comment]
It seems to work for me. It collapses the directory that is selected then selects that directory each time i press it until it is completely collapsed.

Does it select the collapsed directory for you?

**Comment by UziTech** [comment]
Here is a more complete version of the callback function:

```js
callback: () => {
  const editor = atom.workspace.getCenter().getActivePaneItem();
  const filePath = editor && (editor.file && editor.file.path || editor.buffer && editor.buffer.file && editor.buffer.file.path);
  if (filePath) {
    const treeView = atom.packages.getActivePackage("tree-view").mainModule.getTreeViewInstance();
    if (treeView.selectEntryForPath(filePath)) {

      atom.commands.dispatch(
        treeView.element,
        "tree-view:recursive-collapse-directory"
      );
    }
  }
},
```

This will collapse the path for the path for the current active editor

**Comment by slayerxk** [comment]
In my atom it just blink the folder and do nothing, this way did not work at all :/

`module.exports = [
	{
		type: 'button',
		icon: 'gear',
		callback: 'flex-tool-bar:edit-config-file',
		tooltip: 'Edit Tool Bar'
	},
	{
		type: 'button',
		icon: 'angle-left',
		iconset: 'fa',
		callback: () => {
		  const editor = atom.workspace.getCenter().getActivePaneItem();
		  const filePath = editor && (editor.file && editor.file.path || editor.buffer && editor.buffer.file && editor.buffer.file.path);
		  if (filePath) {
		    const treeView = atom.packages.getActivePackage("tree-view").mainModule.getTreeViewInstance();
		    if (treeView.selectEntryForPath(filePath)) {

		      atom.commands.dispatch(
		        treeView.element,
		        "tree-view:recursive-collapse-directory"
		      );
		    }
		  }
		},
		tooltip: 'Collapse Folder',
	}
];`

**Comment by UziTech** [comment]
What versions of Atom, tree-view, and OS are you running?

**Comment by slayerxk** [comment]
Atom - 1.24.1
tree-view@0.221.3
Windows 10 Pro 64-bit

**Comment by UziTech** [comment]
It looks like you have `type: 'button'` instead of `type: 'function'`

**Comment by slayerxk** [comment]
> It looks like you have type: 'button' instead of type: 'function'

It works thanks man !
