### ISSUE TITLE
Add ability to use Font Awesome 5 Free

### ISSUE THREAD

**Issue by HyperHamster** [cakecatz/flex-toolbar#145]
The following is a real example that isn't covered by `"fa"` (Font Awesome 4) in CSON:
```cson
[
  {
    type: "button"
    callback: "application:new-window"
    tooltip: "New Window"
    iconset: "fa5"
    icon: "window-restore"
  }
]
```

**Comment by UziTech** [comment]
The iconsets are loaded by [tool-bar](https://github.com/suda/tool-bar). It would be best to create an issue there
