### ISSUE TITLE
Closing window bug

### ISSUE THREAD

**Issue by robhuska** [cakecatz/flex-toolbar#146]
I know this seems odd, but I have gone through plugins one by one and I have found that this is definitely caused by flex-toolbar...

When flex-toolbar is Enabled and I close my Atom window I am working in, it does something I cannot really describe, but I have screenshots to show.

Before clicking "x" to close the window:
<img width="2048" alt="flex-toolbar-before-close" src="https://user-images.githubusercontent.com/2412155/38627486-1693f8cc-3d7d-11e8-89bc-0e23f9bfa39a.png">

After I click the "x" to close the window:
<img width="2048" alt="flex-toolbar-after-close" src="https://user-images.githubusercontent.com/2412155/38627528-307ba852-3d7d-11e8-9c54-65630c8769cb.png">

So it looks like everything running within the window shuts down, but something stops it and leaves unstyled/unformatted code. Even if I Disable the Tool-Bar package and leave flex-toolbar Enabled, it still does this. It is only when I Disable flex-toolbar that this behavior stops.

macOS 10.13..4
Atom 1.25.1
flex-toolbar 2.0
tool-bar 1.1.7

Let me know if there is anything else I can do to help.

**Comment by UziTech** [comment]
Try this:

1. open Atom
2. open Dev Tools (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>i</kbd>)
3. open Console settings 
   ![image](https://user-images.githubusercontent.com/97994/38628281-9eb81b0e-3d76-11e8-8f9e-fc7e16d8606c.png)
4. Check "Preserve log"
5. Reload Atom (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F5</kbd>)

You should get an error message that will be more descriptive.

I get the same thing occasionally from this bug: https://github.com/atom/grammar-selector/pull/54

**Comment by robhuska** [comment]
Just submitted this and flex-toolbar 2.0.1 showed up for an update. Does not fix the issue. But that reminds me, I cannot confirm right now, but I have a feeling this package is also causing Atom to not restart properly when installing updates. When I click a "Restart" button again Atom starts the process but stalls before completely shutting down, forcing me to have to quit from the Dock.

**Comment by robhuska** [comment]
Before Reload:
<img width="2048" alt="screen shot 2018-04-11 at 12 01 19 pm" src="https://user-images.githubusercontent.com/2412155/38628816-4dd4adb0-3d80-11e8-8ab9-cf0f5fc02827.png">

After Reload:
<img width="2048" alt="screen shot 2018-04-11 at 12 02 42 pm" src="https://user-images.githubusercontent.com/2412155/38628847-616d3e32-3d80-11e8-838e-e4055e149e11.png">

Maybe something to do with devicons? I am not using them in my config.

**Comment by UziTech** [comment]
Does this happen every time you close Atom when `flex-toolbar` is enabled?

**Comment by robhuska** [comment]
Yes, as long as a file is opened.

**Comment by UziTech** [comment]
Try closing atom with dev tools open  when it happens and see if there is a new error that shows up

**Comment by robhuska** [comment]
@UziTech Good call!!
<img width="2048" alt="screen shot 2018-04-11 at 3 06 19 pm" src="https://user-images.githubusercontent.com/2412155/38637690-e9c759ac-3d99-11e8-8a32-124c2b23761c.png">

**Comment by UziTech** [comment]
v2.0.2 should fix it. Thanks for reporting it! 💯

**Comment by robhuska** [comment]
That appears to have done it! Thank you for the quick turn around! 👍
