### ISSUE TITLE
Feature Request: Add filepaths to custom url tokens or allow defining url in callback

### ISSUE THREAD

**Issue by iabw** [cakecatz/flex-toolbar#147]
I would like to extend the behavior of custom urls as implemented in #33 to allow the current file path.

A button I would like to have is to link directly to the history of a file in github. So it would generate a url like https://github.com/cakecatz/flex-toolbar/commits/master/menus/flex-toolbar.cson

For example, I want to be able to either have a button config like
```
{
    type: "url"
    tooltip: "Github History"
    url: "https://github.com/cakecatz/flex-toolbar/commits/master/{file-path}"
    icon: "eye"
  }
```
or
```
{
    type: "url"
    tooltip: "Github History"
    callback: () ->
      file = atom.workspace.config.mainSource.replace({my root filepath here}, "")
      "https://github.com/cakecatz/flex-toolbar/commits/master/#{file}"
    icon: "eye"
  }
```

preferably the second one, to be able to do things like remove root directories as my callback is doing, or you could imagine 2 slightly different filepaths and this button would link to a sister file of the open file, etc.

I'm not familiar with Atom's API, having done no direct development with it, so I'm not sure if there's alternative hooks to workspace.config.mainSource

Thanks. :)

**Comment by UziTech** [comment]
the second example should work already if you use a `.coffee` config file and a `type: "function"` button

**Comment by iabw** [comment]
```
    type: "function"
    tooltip: "Github History"
    callback: () ->
      file = atom.workspace.config.mainSource.replace({my root filepath here}, "")
      "https://github.com/cakecatz/flex-toolbar/commits/master/#{file}"
    icon: "eye"
}
```
doesn't work.

The callback returns the correct string, but it doesn't know to call shell.openExternal with the result as seen at https://github.com/cakecatz/flex-toolbar/blob/master/lib/types/url.js#L28

**Comment by UziTech** [comment]
sorry I meant a function would work. To get it to open the webpage you could do something like:

```coffee
{shell} = require "electron"
...
  callback: (editor) ->
    file = editor?.getPath?()
		return unless file?
    relativeFile = atom.project.relativizePath(file)[1];
    url = "https://github.com/cakecatz/flex-toolbar/commits/master/#{relativeFile}"
		shell.openExternal(url)
    
```

I have not tested this so there could be bugs

**Comment by iabw** [comment]
It didn't occur to me that since this is a coffee file I'd be able to import modules. I also didn't realize I could use a .js file, so I've converted to that, and have it working.

Full minimal example:
```
var electron = require( "electron" );

module.exports = [
  {
    type: "function",
    tooltip: "Github History",
    callback: function (editor) {
      var file = editor && editor.getPath && editor.getPath();
      if ( file ) {
        var relativeFile = atom.project.relativizePath( file )[ 1 ];
        var url = `https://github.com/cakecatz/flex-toolbar/commits/master/${ relativeFile }`;
        return electron.shell.openExternal( url );
      }
    },
    icon: "eye"
  }
]
```

I think this could be documented a little better, but my issue is definitely close-able.

Thanks for helping me realize the full power I knew was hidden in there!

**Comment by UziTech** [comment]
Good to hear.

If you want to submit a PR to make the docs better for the next person who wants this, that would be much appreciated. 👍
