### ISSUE TITLE
Change toolbar button when changed grammar

### ISSUE THREAD

**Issue by cakecatz** [cakecatz/flex-toolbar#15]
![preview](http://i.gyazo.com/ba3a55256b3fa966c0a839539d0d39e9.gif)

**Comment by cakecatz** [comment]
toolbar.json is like this :)
![screen shot 2015-05-08 at 2 00 22 pm](https://cloud.githubusercontent.com/assets/6136383/7530836/a8323ef8-f58a-11e4-89d4-b0f0d7818cff.png)

**Comment by jerone** [comment]
Great concept! 

Just some thoughts:

I think I like it more if the buttons get disabled instead of removed when switching grammar.

What about multiple grammars -> e.g. `{ "grammar": "CoffeeScript,JavaScript" }` 

What about all **except** one (or more) grammar(s) -> e.g. `{ "grammar": "!coffeescript" }`

**Comment by cakecatz** [comment]
> What about multiple grammars -> e.g. { "grammar": "CoffeeScript,JavaScript" }
> 
> What about all except one (or more) grammar(s) -> e.g. { "grammar": "!coffeescript" }

Cool!!

> I think I like it more if the buttons get disabled instead of removed when switching grammar.

Hmm, I think if each project use different languages, probably ToolBar have many disused buttons. 
So I want to hide(remove) it for ToolBar to clean. (but high cost)

Porting is good :+1:

**Comment by jerone** [comment]
[**@cakecatz**](https://github.com/cakecatz) commented on [8 mei 2015 14:43 CEST](https://github.com/cakecatz/flex-toolbar/issues/15#issuecomment-100221815 "2015-05-08T12:43:37Z - Replied by Github Comment Enhancer"):
> > I think I like it more if the buttons get disabled instead of removed when switching grammar.
> 
> Hmm, I think if each project use different languages, probably ToolBar have many disused buttons.   

I understand your point. My issue is that with hiding the buttons, others shift to the left and won't stay on the same place as I have placed and get to know them.

Anyways, this could always be an option.

**Comment by jerone** [comment]
:+1: Will try it out soon.

**Comment by cakecatz** [comment]
:smile:

**Comment by jerone** [comment]
I tried and worked like documented in readme :+1: 

I noticed that you chanced the key from `"grammar"` to `"hide"`, which is a bit confusing to me. The key has nothing to do with grammars, which begins confusing. Second, it looks like this is reverse. I think the most use-cases for this is to show the button only for some grammars. Not to specify all grammars I don't want to be shown. Now I have to inverse (`!`) all grammars. For example the Markdown Preview button, I want to only show it with grammar markdown. Now I have to specify:
```
"hide": "!markdown"
```
While it's more logic to use:
```
"grammar": "markdown"
```

Does this makes sense? It's late :)

**Comment by cakecatz** [comment]
That is certainly true :disappointed: 
I'll add 2 properties `show` and `enable`.

**Comment by jerone** [comment]
Found a bug: button won't hide/show on panes without a grammar; e.g. the settings window.

It still sounds confusing to me :disappointed:  There are now multiple different situations; `show`, `hide`, `enable`, `disable`, with or without `!`...

Why not go with your original draft and my comment on that:

* If no `grammar` is defined, default show the button.
* When `grammar` is defined, default hide the button, show button with specified grammars:
```
{ "grammar": "coffeescript" }
{ "grammar": "coffeescript,javascript" }  // multiple
```
* When `grammar` is defined, and the grammar is prefixed with an exclamation mark `!`, default show the button, hide button with specified grammars:
```
{ "grammar": "!coffeescript" }
{ "grammar": "!coffeescript,!javascript" }  // multiple
```

Besides using the property `grammar` is instant clear that it's about grammars, the properties `show`/`hide` might conflict with (maybe) future plans to attach visibility conditions to toggle button state in the tool-bar package.

Anyways, just some thoughts. Keep up the great work!
