### ISSUE TITLE
Is it possible to disable button if !tex ?

### ISSUE THREAD

**Issue by NicklasVraa** [cakecatz/flex-toolbar#152]
Have tried all the obvious things as the grammer value, such as tex, latex, Latex etc.

**Comment by UziTech** [comment]
try `text.tex`

**Comment by UziTech** [comment]
`disable: "!tex"` should work.

It looks at the grammer name.

![image](https://user-images.githubusercontent.com/97994/43430990-5f74f3ce-9431-11e8-869e-9a23cc936103.png)

**Comment by UziTech** [comment]
It actually checks if the grammar name **contains** the string.

`disable: "!tex"` should disable the button on any grammar that does not contain the string `tex`

**Comment by UziTech** [comment]
or you can also do:

`enable: "tex"`

This should enable the button only on grammars that contain the string `tex`

**Comment by NicklasVraa** [comment]
Have a button to compile pdf, that i want disabled, if the file is not markdown or tex.
Have tried:
```
disable: {
  grammar: [
    "!Markdown"
    "!tex"
  ]
}

Is toolbar not interpreting this as: if not markdown **OR** not tex?.

Have also tried
```
enable: {
  grammer: [
    "Markdown"
    "tex"
  ]
}

**Comment by UziTech** [comment]
looks like gramm**a**r was spelled wrong on your `enable`

the array is an **OR**

Glad you solved it 😃 👍
