### ISSUE TITLE
Change the font-size of button doesn't work

### ISSUE THREAD

**Issue by JInfantesC** [cakecatz/flex-toolbar#155]
I'm trying to change the font-size of my button using:
```cson
{
        type: 'button'
        text: 'Lint'
        tooltip: 'Lint current file'
        dependency: 'linter'
        callback: 'linter:lint'
        style:{
            font-size: "12px";
        }
    }
```
but the toolbar disappear after saving the file.
I've tried changing the font-size on the inspector and it works great, but it seems that flex-toolbar doesn't accept this option to be changed here.

**Comment by UziTech** [comment]
Try quotes around `"font-size"`

**Comment by JInfantesC** [comment]
Thank you for answering so quickly.
Quotes works perfectly.
