### ISSUE TITLE
Show for particular package not working

### ISSUE THREAD

**Issue by binaryfunt** [cakecatz/flex-toolbar#158]
For some reason, when I have
```
show: {
  package: "quick-fold"
}
```
in `toolbar.cson`, the button doesn't show, even though I have [quick-fold](https://atom.io/packages/quick-fold) installed. This is a package I recently created and published - the development version is only linked in dev mode and I installed the release version the usual way after publishing (and it's not disabled). If I change `"quick-fold"` it to another, older package I maintain and have a dev version of, the button re-appears.

I don't get any errors/warnings in the console.

**Comment by UziTech** [comment]
try typing `atom.packages.isPackageActive("quick-fold")` into the console and see what it returns.

**Comment by UziTech** [comment]
It could be that the package is installed but not active. (i.e. no activation command was dispatched)

**Comment by UziTech** [comment]
maybe we should change it to check if the package is loaded instead of active?

**Comment by binaryfunt** [comment]
> try typing atom.packages.isPackageActive("quick-fold") into the console and see what it returns.

Indeed, returns `false`. It seems my package doesn't activate until I run the (only) command it has. Is this a problem?

> maybe we should change it to check if the package is loaded instead of active?

`atom.packages.isPackageLoaded("quick-fold")` returns `true`

**Comment by UziTech** [comment]
> Is this a problem

No, packages like `quick-fold` that have a command that needs to run should defer activating until the command is called so they don't affect startup time.

It seems like the `"package"` condition should return true if it is loaded not just active but I don't know if changing it now would break someones expectation.
