### ISSUE TITLE
ion iconset stop working

### ISSUE THREAD

**Issue by Mayccoll** [cakecatz/flex-toolbar#161]
Atom:
1.40.1 x64
OS:
Linux Mint
Flex Toolbar:
2.1.4

I'm not sure how to debug this and `ion` set stop working.
Send screen shot.
Thanks
![Selection_001](https://user-images.githubusercontent.com/2009698/66057760-e1a4a280-e4fe-11e9-9f97-a9c568495423.png)

**Comment by UziTech** [comment]
probably has something to do with `tool-bar` updateing ion icons in https://github.com/suda/tool-bar/pull/263

I'm investigating

**Comment by UziTech** [comment]
try adding `md-` before the icon name `close -> md-close`

**Comment by suda** [comment]
It's a [bug introduced in 1.1.13](https://github.com/suda/tool-bar/issues/264), we're working on a fix for it.

**Comment by Mayccoll** [comment]
Right adding the `md-` fix the issue. 
https://ionicframework.com/docs/v3/ionicons/
Thanks
