### ISSUE TITLE
Missing some octicons icons

### ISSUE THREAD

**Issue by Shadowfita** [cakecatz/flex-toolbar#162]
Hi,

Sorry if this is not really an issue. I've been loving this so far but have found that some of the icons in the default set (that are on the website) don't work in the plugin. Such as: https://octicons.github.com/icon/play/ . Just comes up as blank.

Thanks!

**Comment by UziTech** [comment]
The icons are handled by the [`tool-bar`](https://github.com/suda/tool-bar) package

**Comment by UziTech** [comment]
It looks like octicons are actually installed by Atom https://github.com/atom/atom/blob/master/static/icons/octicons.less

It would probably be better to create an issue there.

**Comment by Shadowfita** [comment]
Thanks for that!
