### ISSUE TITLE
Feature: tree-view:toggle-ignored-names

### ISSUE THREAD

**Issue by svoop** [cakecatz/flex-toolbar#163]
The prefs contain the following two settings:

<img width="443" alt="Screen Shot 2019-11-20 at 13 12 04" src="https://user-images.githubusercontent.com/7255/69238080-6161fb80-0b97-11ea-9c17-d98556d13f4f.png">

The latter is available as command `tree-view:toggle-vcs-ignored-files`. Would it be very complicated to make the first one available as command as well, e.g. `tree-view:toggle-ignored-names`.

Background: I'd like to add a button to my flexbar which toggles the two settings thus showing/hiding those ignored files in the tree view.

Thanks for considering this addition!

**Comment by UziTech** [comment]
You can add a button that runs a command like this:

```
{
  type: "button"
  text: "Ignore Files"
  callback: "tree-view:toggle-vcs-ignored-files"
},
{
  type: "button"
  text: "Ignore Names"
  callback: "tree-view:toggle-ignored-names"
}
```

To create the commands you will need to create an issue in the [tree-view](https://github.com/atom/tree-view) repo.

Or you could add a command yourself in your init file:
1. run `application:open-your-init-script`
2. write code to create the command. Something like:
   ```
   atom.commands.add("atom-workspace", "tree-view:toggle-ignored-names", {
     didDispatch: () => {
       atom.config.set("tree-view.hideIgnoredNames", !atom.config.get("tree-view.hideIgnoredNames"))
     }
   });
   ```

**Comment by svoop** [comment]
Ah, stupid me, this is of course the wrong place for this issue. However, thanks a bunch for the hints!

**Comment by svoop** [comment]
In case someone else stumbles onto this issue:

```
# Expose command to toggle ignored names in tree-view
atom.commands.add "atom-workspace", "tree-view:toggle-ignored-names", ->
  atom.config.set("tree-view.hideIgnoredNames", !atom.config.get("tree-view.hideIgnoredNames"))
```

**Comment by UziTech** [comment]
Thanks, my init script is in javascript, I forgot the default is coffeescript.

**Comment by svoop** [comment]
Works like a charm, thanks @UziTech !
