### ISSUE TITLE
Icons from icon set ion not found

### ISSUE THREAD

**Issue by RalfLangeDresden** [cakecatz/flex-toolbar#166]
Hi,
new installed flex-tool-bar can't find the icons in iconsets ion and fa.
Operating system: Linux and Windows
Atom version: 1.43.0 x64
Flex-tool-bar version: 2.1.4
You can see it in the attached picture.
How can I fix this problem?

Thanks.
Ralf

![atom-flex-tool-bar](https://user-images.githubusercontent.com/23308829/73057832-b6b9d200-3e92-11ea-9d8c-0241c07ccfa3.png)

**Comment by UziTech** [comment]
tool-bar uses ion v4. Try prefixing ion icons with `md-` (i.e. `md-document`)
