### ISSUE TITLE
Toggle icon button

### ISSUE THREAD

**Issue by MaximeWillinger** [cakecatz/flex-toolbar#19]
Hi,

I would like to know if it is possible to change a button icon when we use a toggle action ? (exemple : changing a chevron direction when we open or close a pane).

If it is not, do you think that it would be a good feature to implement ?

Waiting for you feedbacks,
Max

**Comment by jerone** [comment]
> I would like to know if it is possible to change a button icon when we use a toggle action ?

No, not right now.

But it's a good feature suggestion for https://github.com/suda/tool-bar

I've been thinking about this too for a while now. Problem is that it's hard to know which state (active or inactive) a button should be in. Say I want a toggle button for Markdown Preview. How does the toggle button know which state it should be in? When pressed it could be set to active, and when pressed again it could be restored to inactive. Problem is that Markdown Preview could be closed manually, or called by a command. The toggle button doesn't know about those methods.

I do like the idea, but I don’t know how to solve this technically.

**Comment by MaximeWillinger** [comment]
Yes, I actually had the same conclusion.

I don't know well how Atom internally works. Maybe, it could be possible to intercept every command executed by the core and the plugins, so we can update our button state when one of the toggle used in the bar is fired.

Te real problem is to get the original state of a toggle ...

**Comment by MaximeWillinger** [comment]
Any news @jerone ?

**Comment by jerone** [comment]
[**@MaximeWillinger**](https://github.com/MaximeWillinger) commented on [28 mei 2015 10:48 CEST](https://github.com/cakecatz/flex-toolbar/issues/19#issuecomment-106235979 "2015-05-28T08:48:43Z - Replied by Github Comment Enhancer"):
> Any news [@jerone](https://github.com/jerone) ?

This is now part of https://github.com/suda/tool-bar/issues/43

**Comment by MaximeWillinger** [comment]
Thank you! I close this issue.

**Comment by c10b10** [comment]
How would I enable toggle for a certain button defined in flex-toolbar?

**Comment by cakecatz** [comment]
@c10b10 Sorry, It is not available now.
It will become available after https://github.com/suda/tool-bar/issues/43 implemented.
