### ISSUE TITLE
Support/documentation request - calling platformioIDETerminalService from a callback function

### ISSUE THREAD

**Issue by tobyink** [cakecatz/flex-toolbar#193]
I'd like to use `type: "button"` to call the `platformioIDETerminalService` service provided by another Atom package.

Is this possible? How?

**Comment by UziTech** [comment]
You can use [terminal-commands](https://atom.io/packages/terminal-commands). I don't think there is an official way to create a service provider that is not a package. You can use `type: "function" ` to run any code you want when the button is clicked.

**Comment by tobyink** [comment]
Yeah, I have been using terminal-commands so far.

But flex-toolbar has the rather cool feature of project-specific config files, while terminal-commands does not — it just has a single global config. So if I want to create a toolbar button for one particular project, which runs `rsync -vr assets user@somehost:public_html/` then I need to create that in my global terminal-commands config and then call that from the project-specific flex-toobar config. I would much rather, if it's somehow possible, configure any project-specific buttons entirely in `toolbar.coffee`.

**Comment by tobyink** [comment]
Okay, this is pretty horrible, but works for me and I'm satisfied with it. It grabs the name of the file currently being edited, and runs `ls -l` on it. Yes, it's very specific to one particular terminal package, but I'm okay with that.

```
  {
    type: "function"
    tooltip: "ls -l"
    icon: "list"
    iconset: "fa"
    callback: (target) ->
      fn = target.buffer.file.path
      srv = atom.packages.activePackages['x-terminal'].mainModule.getInstance().providePlatformIOIDEService()
      srv.run( ['ls -l ' + fn ] )
  }
```
