### ISSUE TITLE
Uncaught Error: watch ENOENT

### ISSUE THREAD

**Issue by pauloabmiranda** [cakecatz/flex-toolbar#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.205.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.4.0

### Stack Trace

Uncaught Error: watch ENOENT

```
At fs.js:1228

Error: watch ENOENT
  at exports._errnoException (util.js:734:11)
  at FSWatcher.start (fs.js:1228:11)
  at Object.fs.watch (fs.js:1254:11)
  at watch (H:\LiberKey\MyApps\atom\packages\flex-tool-bar\node_modules\node-watch\lib\watch.js:221:8)
  at H:\LiberKey\MyApps\atom\packages\flex-tool-bar\node_modules\node-watch\lib\watch.js:230:9
  at H:\LiberKey\MyApps\atom\packages\flex-tool-bar\node_modules\node-watch\lib\watch.js:41:14
  at Array.forEach (native)
  at H:\LiberKey\MyApps\atom\packages\flex-tool-bar\node_modules\node-watch\lib\watch.js:38:18
  at ATOM_SHELL_ASAR.js:433:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "deprecation-cop"
    ],
    "useReactEditor": true,
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.6.4
autoclose-html, v0.17.0
css-color-highlighting, v0.2.4
editor-stats, v0.17.0
emmet, v2.3.10
filetype-color, v0.1.4
flex-tool-bar, v0.4.0
highlight-line, v0.10.2
jshint, v1.3.7
linter, v0.12.6
linter-scss-lint, v1.0.4
pigments, v0.4.4
project-manager, v1.15.7
seti-ui, v0.7.1
show-in-folder, v0.1.0
symbols-tree-view, v0.9.3
tool-bar, v0.1.5
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by cakecatz** [comment]
@pauloabmiranda Hmm, I can't reproduce it...
Where's your config file path?
I think atom not have permission  to that directory,file or not exists.

**Comment by jerone** [comment]
And do you have a `toolbar.json` file in your ~Atom directory?

**Comment by pauloabmiranda** [comment]
Sorry for the late reply,

I have a portable version of the Atom and i have the config file in this
path
H:\LiberKey\MyApps\atom
and the app is in this path H:\LiberKey\MyApps\atom\app-0.206.0
The portable version was introduced in Atom this year.
In Windows add ATOM_HOME to the Path and Atom saves everything in that
place including the packages and configurations.

Hope this explains everything.

**Comment by pauloabmiranda** [comment]
I don't have a toolbar.json.
With the last update i have no error anymore.

**Comment by jerone** [comment]
"...last update..." means which version?

"...no error anymore." So this issue can be closed?

**Comment by pauloabmiranda** [comment]
sorry 0.4.2 and i will close it.
