### ISSUE TITLE
Buttons show on different grammar

### ISSUE THREAD

**Issue by CPterion** [cakecatz/flex-toolbar#233]
Even when specified to show only when the grammar is "C," the buttons still show when a .cson file is opened.

**Comment by UziTech** [comment]
Can you share your config and versions for Atom and OS?

**Comment by CPterion** [comment]
**Configuration:**
```CSON
{
	type: "button"
	icon: "triangle-right"
	callback: "process-palette:compile"
	tooltip: "Compile code"
	show:
		grammar: "C"
}
```
**Atom Version:** 1.54.0
**Operating System:** Windows 7

I tried opening a .cpp file, and it also shows the button as well. For now, I'm using `pattern: "*.c"` so that it won't appear on .cson or .cpp files.

**Comment by UziTech** [comment]
Nice catch. Looks like that bug has been there for over 5 years!!
