### ISSUE TITLE
Buttons are not shown after hide or disable in empty window

### ISSUE THREAD

**Issue by KabbAmine** [cakecatz/flex-toolbar#24]
Hi, first of all thanks for your awesome plugin.

When Atom starts with an empty window, and I have `hide` or `disable` on a button X, the buttons after X are not shown until I create/open a new file :confused: 

The following gif will be more explicit:
![atom](https://cloud.githubusercontent.com/assets/5658084/8005043/51b5442a-0b8e-11e5-924d-d6b754d64733.gif)

There is my `toolbar.json`:
```json
[
    {
        "type": "button",
        "icon": "arrow-right",
        "callback": "toolbar:toggle",
        "tooltip": "Toggle toolbar",
        "iconset": ""
    },
    {
        "type": "spacer"
    },
    {
        "type": "button",
        "icon": "qr-scanner",
        "callback": "minimap:toggle",
        "tooltip": "Toggle mini-map",
        "iconset": "ion"
    },
    {
        "type": "button",
        "icon": "columns",
        "iconset": "fa",
        "callback": ["pane:split-right"]
    },
    {
        "type": "button",
        "icon": "file-directory",
        "callback": "tree-view:toggle",
        "tooltip": "Toggle tree view",
        "iconset": ""
    },
    {
        "type": "button",
        "icon": "terminal",
        "callback": "terminal-panel:toggle",
        "tooltip": "Open terminal here",
        "iconset": ""
    },
    {
        "type": "button",
        "icon": "code",
        "callback": "symbols-tree-view:toggle",
        "tooltip": "Toggle symbols tree view",
        "iconset": ""
    },
    {
        "type": "spacer"
    },
    {
        "type": "button",
        "icon": "git-branch",
        "callback": "git-log:show",
        "tooltip": "Show Git log",
        "iconset": ""
    },
    {
        "type": "button",
        "icon": "globe",
        "callback": "browser-plus:open",
        "tooltip": "Show web browser plugin",
        "iconset": ""
    },
    {
        "type": "button",
        "icon": "markdown",
        "callback": "markdown-preview:toggle",
        "tooltip": "Show web browser plugin",
        "iconset": "",
        "hide": "!markdown"
    },
    {
        "type": "spacer"
    },
    {
        "type": "button",
        "icon": "sync",
        "callback": "window:reload",
        "tooltip": "Reload Atom",
        "iconset": ""
    },
    {
        "type": "button",
        "icon": "settings",
        "callback": "settings-view:open",
        "tooltip": "Open/Show settings",
        "iconset": ""
    }
]
```

**Comment by jerone** [comment]
Confirmed.

**Comment by KabbAmine** [comment]
That was quick :smiley:

**Comment by jerone** [comment]
[**@KabbAmine**](https://github.com/KabbAmine) commented on [5 jun. 2015 13:28 CEST](https://github.com/cakecatz/flex-toolbar/issues/24#issuecomment-109263461 "2015-06-05T11:28:00Z - Replied by Github Comment Enhancer"):
> That was quick ![:smiley:](https://assets-cdn.github.com/images/icons/emoji/unicode/1f603.png ":smiley:")

Noticed it when testing the feature, it got merged before I got time to write a good bug report. You just remembered me :smile:

**Comment by cakecatz** [comment]
@KabbAmine  Thanks for reporting issue :relaxed: 
Fixed at 0.4.2 and did publish it just now.

**Comment by KabbAmine** [comment]
Works great, thanks.
I close the issue.

**Comment by jerone** [comment]
This issue has appeared again in latest version...
![screenshot](https://cloud.githubusercontent.com/assets/55841/11724240/2431796e-9f73-11e5-8040-1b44d55a2d9e.gif)

Atom 1.4.0-beta0
Flex-tool-bar 0.7.0

**Comment by cakecatz** [comment]
:sob:

**Comment by jerone** [comment]
I tracked it down to https://github.com/cakecatz/flex-toolbar/commit/e14eb3a7ab310e981fc1e19b2a2097794e3d069f#diff-24c93f2143f6bcedf1a1775cb7b798d0R138 which searches for `atom.workspace.getActiveTextEditor()` resulting in `undefined` as there are no editors on first open (see screenshot [above](https://github.com/cakecatz/flex-toolbar/issues/24#issuecomment-163708839))!

https://github.com/cakecatz/flex-toolbar/commit/e14eb3a7ab310e981fc1e19b2a2097794e3d069f#diff-24c93f2143f6bcedf1a1775cb7b798d0R126 probably triggers the same issue.

Bug introduced in https://github.com/cakecatz/flex-toolbar/pull/50

/cc @boredz
