### ISSUE TITLE
Failed to activate the flex-tool-bar package

### ISSUE THREAD

**Issue by JoeNoPhoto** [cakecatz/flex-toolbar#25]
[Enter steps to reproduce below:]

1. started Atom via terminal

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.4.2

### Stack Trace

Failed to activate the flex-tool-bar package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.resolveConfigPath (/Users/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:165:12)
    at Object.module.exports.activate (/Users/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:29:12)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "jquery-snippets"
    ],
    "projectHome": "/Users/Projects",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
block-cursor, v0.12.5
color-picker, v2.0.4
emmet, v2.3.10
file-icons, v1.5.7
flex-tool-bar, v0.4.2
git-log, v0.4.1
javascript-snippets, v1.0.0
language-babel, v0.7.0
language-javascript-jsx, v0.3.6
linter, v0.12.6
linter-csslint, v0.0.13
linter-eslint, v0.5.8
linter-htmlhint, v0.0.16
linter-scss-lint, v1.0.4
linter-tidy, v1.0.1
local-history, v3.2.2
minimap, v4.9.4
minimap-autohide, v0.10.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
project-manager, v1.15.8
script, v2.23.0
tool-bar, v0.1.5

# Dev
No dev packages
```

**Comment by jerone** [comment]
Did you download this package through Atom or apm, or forked it in git?

Can you check if the folder `node_modules` within this package directory contains a folder `fs-plus`?

**Comment by JoeNoPhoto** [comment]
I downloaded through Atom. It was working without error for at least a week without error. 

Also, I've confirmed fs-plus is contained within node_modules.

**Comment by jerone** [comment]
[**@JoeNoPhoto**](https://github.com/JoeNoPhoto) commented on [5 jun. 2015 20:47 CEST](https://github.com/cakecatz/flex-toolbar/issues/25#issuecomment-109395364 "2015-06-05T18:47:38Z - Replied by Github Comment Enhancer"):
> Also, I've confirmed fs-plus is contained within node_modules. (/Applications/Atom.app/Contents/Resources/app/apm/node_modules)

It should be within `~\.atom\packages\flex-tool-bar\node_modules`.

**Comment by JoeNoPhoto** [comment]
Sorry. It's there as well.

**Comment by jerone** [comment]
[**@JoeNoPhoto**](https://github.com/JoeNoPhoto) commented on [5 jun. 2015 21:39 CEST](https://github.com/cakecatz/flex-toolbar/issues/25#issuecomment-109416058 "2015-06-05T19:39:30Z - Replied by Github Comment Enhancer"):
> Sorry. It's there as well. only file is LICENSE.md

Ah, there should be more files in that folder. Then something went wrong with apm installing `fs-plus` node.js package. If you have experience with node.js, you can install it manually (`npm install fs-plus`). Otherwise I recommend to uninstall and then reinstall this package again.

**Comment by JoeNoPhoto** [comment]
Uninstall seemed to do the trick. Thanks.
