### ISSUE TITLE
Execute shell commands

### ISSUE THREAD

**Issue by lwis** [cakecatz/flex-toolbar#26]
Instead of callbacks, would it be possible to execute commands with the project as the working directory?

**Comment by cakecatz** [comment]
@lwis It is possible, but can't use it on current package :pensive:
Actually, I implemented it on my local.
If you want to use, I release it on next version :wink:

**Comment by lwis** [comment]
Please, and thank you! :smile:

**Comment by jerone** [comment]
@lwis or @cakecatz Can you give an example of shell commands?

**Comment by mateosss** [comment]
Oh please I really need this feature.

**Comment by VladShcherbin** [comment]
+1

**Comment by mateosss** [comment]
I found a workaround. With atom-build  https://atom.io/packages/build
You can configure a custom build command to execute when you hit a button on the flex toolbar.

**Comment by UziTech** [comment]
I am doing this by using [terminal-commands](https://atom.io/packages/terminal-commands) to create commands for a button.

**Comment by UziTech** [comment]
I am going to close this as it is out of the scope of this project to display any sort of output from a shell command.

You can accomplish this by using [terminal-commands](https://atom.io/packages/terminal-commands) to create commands for the command palette , then using those commands as the callback of a button.

You can also use a function button to call your own commands.
