### ISSUE TITLE
Update the type 'spacer' and add the ability to change color for compatibility with dark styles

### ISSUE THREAD

**Issue by artctv** [cakecatz/flex-toolbar#264]
Hello! 
Is it possible to change the style that the `spacer` is assigned to in order to be able to assign it a certain color? Dark color is poorly compatible with dark atom interfaces:
![image](https://user-images.githubusercontent.com/37845518/135855454-211a47c9-eda6-4c06-b3e0-a7e82aa1736d.png)

The only way that color changes:
```
.tool-bar {

   &[class*='tool-bar-'] {
      .tool-bar-spacer {
         border: 0.05em solid #ffffff;
         opacity: 40%;
      }
   }
}
```
With this style:
![image](https://user-images.githubusercontent.com/37845518/135855296-845ead6e-a01f-48ae-88f2-4499789dbde8.png)
But, i think this is very strange

**Comment by UziTech** [comment]
You could use `!important` if you don't want the `&[class...` but that is how you should change the color.

**Comment by artctv** [comment]
I'm not that good at js and css, but it seems that the `spacer` is not made by such an element that can change color, or am I wrong?

**Comment by artctv** [comment]
@UziTech Thank you, I got it!
