### ISSUE TITLE
Change the icon size

### ISSUE THREAD

**Issue by Diullei** [cakecatz/flex-toolbar#27]
how can I change the icon size for a small size?

**Comment by cakecatz** [comment]
@Diullei From `tool-bar` settings :)

![screen shot 2015-06-12 at 2 29 47 pm](https://cloud.githubusercontent.com/assets/6136383/8124038/913707a6-110f-11e5-993f-bd395ae23028.png)

**Comment by Diullei** [comment]
So easy! :) ... Thank you!

**Comment by Spidersouris** [comment]
Is it possible to change the icon size of one icon only?
