### ISSUE TITLE
Edit Config File option in command palette opens a new untitled document

### ISSUE THREAD

**Issue by jluchiji** [cakecatz/flex-toolbar#29]
When I choose `Flex Tool Bar: Edit Config File` option, I get a new untitled pane open instead of the configuration file.

**Comment by cakecatz** [comment]
@jluchiji Is there `toolbar.cson(json, json5)` in `~/.atom/` directory?

**Comment by jluchiji** [comment]
Initially, no. I read through the source code and created the `toolbar.json`, which did not work for me. I also tried manually setting the `flex-tool-bar.toolBarConfigurationFilePath` config to `toolbar.json`, which did not solve the issue either.

**Comment by cakecatz** [comment]
@jluchiji :persevere: 
What's your OS?

**Comment by jluchiji** [comment]
I'm on OSX 10.10.3.
Somehow the issue just fixed itself after a complete reboot... now the toolbar seems to work just fine.

**Comment by duanefields** [comment]
For what it's worth, I had this same issue, OSX 10.10.4

**Comment by jerone** [comment]
@cakecatz It looks like the file (`toolbar.json` or `toolbar.cson`) is never actually created. On activation a check is done to check if the file exists (`resolveConfigPath`), but when it doesn't the variable `configFilePath` will be empty until a new restart is done.

**Comment by cakecatz** [comment]
@jerone Exactly! Thanks :laughing:
