### ISSUE TITLE
JSON load error

### ISSUE THREAD

**Issue by adouglas** [cakecatz/flex-toolbar#30]
Hi, I've just updated to 0.4.3 and flex stopped working complaining of an error:

    ~/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:79
    JSON is not valid

I checked the JSON file (which was simple and valid), tried restarting, disabling and reenabling both flex and toolbar but to no avail. Then I converted the JSON to CSON (and renamed the file) and the toolbar reappeared.

**Comment by cakecatz** [comment]
@adouglas Thanks for reporting ;)

**Comment by igorprado** [comment]
I came here for the same reason. It's happening with me too :)

Atom 1.0.2
Tool bar 0.1.8
Flex tool bar 0.4.3

**Comment by adouglas** [comment]
#31 Should have fixed this. Works for me, can someone else test as well and if happy close this :)

**Comment by igorprado** [comment]
@adouglas Yeah, it's working now! :)
