### ISSUE TITLE
Dynamic URL

### ISSUE THREAD

**Issue by FabianMeul** [cakecatz/flex-toolbar#33]
Hi, 

Is it possible to create dynamic URL's in the toolbar?
I would like to create a link that, when pressed, opens the current projects' 'bitbucket' page.

Below is an example of what I want to achieve. (Don't mind the syntax, it's conceptual ;-) )
  {
    type: "url"
    iconset: "fa"
    icon: "bitbucket"
    url: "http://bitbucket.org" + urlToRepo
    tooltip: "Bitbucket Page"
  }

Thx a bunch!

**Comment by jerone** [comment]
Interesting idea. Maybe make it possible to use a few tokens within the url. Tokens like:
* repo name
* repo owner
* current project name
* atom version
* ...

And use it like:
```
{
    type: "url"
    icon: "octoface"
    url: "http://github.com/{repo-owner}/{repo-name}"
    tooltip: "Github Page"
  }
```

**Comment by cakecatz** [comment]
@FabianMeul Yes :smile: 
It's not difficult. 
I'll try implement it with jerone's syntax. (Thanks @jerone)

**Comment by FabianMeul** [comment]
Great! :+1: 

Looking forward to the implementation. :-)

**Comment by jerone** [comment]
This has been implemented https://github.com/cakecatz/flex-toolbar/commit/8ba0b5101b951627ee47064108bb1fa5150ca813

**Comment by TigersWay** [comment]
Hi,
Nice feature, but could it be extended to **project-name**?

**Comment by UziTech** [comment]
@TigersWay you can extend it by adding to the `@info` object in `./lib/url-replace.coffee` If you create a PR I could merge it.

https://github.com/cakecatz/flex-toolbar/blob/a6ddf1691e984fa299be97885c4f5c0d6bb8f150/lib/url-replace.coffee#L5-L8
