### ISSUE TITLE
Supported icon sets?

### ISSUE THREAD

**Issue by danielbayley** [cakecatz/flex-toolbar#35]
Octicons seems to work fine, but according to the [main tool-bar package](https://atom.io/packages/tool-bar) these icon sets should be supported;

Ionicons (`ion`)
FontAwesome (`fa`)
Foundation (`fi`)
IcoMoon (`icomoon`)
Devicon (`devicon `)

However adding `icon: "set-icon-name"` doesn't appear to work.

**Comment by jerone** [comment]
You don't need to prefix the icon with the iconset name. e.g.:
```cson
  {
    type: "button"
    icon: "document"
    callback: "application:new-file"
    tooltip: "New File"
    iconset: "ion"
  }
```

Thus **not** `icon: ion-document` but `icon: document`.

**Comment by danielbayley** [comment]
Nice one, cheers. :thumbsup:
