### ISSUE TITLE
Contextual menu item to Edit Toolbar[.cson]

### ISSUE THREAD

**Issue by danielbayley** [cakecatz/flex-toolbar#36]
…rather than take up a button.

**Comment by jerone** [comment]
I was just going to suggest that :bulb: :+1: 

To make this work right now you can add the following code to your `init.coffee` file:
```coffeescript
# Add edit tool-bar to ToolBar contextMenu
toolBarContextMenu = atom.contextMenu.itemSets.filter (item) ->
  item.selector is '.tool-bar'
toolBarContextMenu?[0]?.items.push
  command: 'flex-tool-bar:edit-config-file'
  label: '&Edit Tool Bar'
  selector: '.tool-bar'
```

**Comment by danielbayley** [comment]
Thanks, I converted to PR #39.

**Comment by Zeioth** [comment]
I would suggest to do not hardcoding an "Edit Toolbar" button into the toolbar. it would be cleaner to put it into the addon settings. This way you are not obligated to have this button in the toolbar if you don't want to.
