### ISSUE TITLE
Execute hotkeys

### ISSUE THREAD

**Issue by WebFreak001** [cakecatz/flex-toolbar#41]
It would be useful If a callback could be a hotkey, so I can run commands with plugins that dynamically define hotkeys

**Comment by cakecatz** [comment]
Is it like this?
```
callback: 'ctrl-x'
```
Do I understand it correctly?

**Comment by WebFreak001** [comment]
Yeah exactly like that

**Comment by cakecatz** [comment]
OK!
Could you make PR?:smirk:

**Comment by WebFreak001** [comment]
I can try, I hate debugging or loading development packages in atom

**Comment by jerone** [comment]
Correct me if I misunderstood, but doesn't every keystroke/hotkey have a command attached to it?

Even the keystroke `ctrl-x` has the command `core:cut`...

You can check Atom settings > Keybindings for every command attached to every keystroke.

**Comment by WebFreak001** [comment]
https://atom.io/packages/build in this package for example you can define custom keybinds that are not assigned to a specific command

**Comment by jerone** [comment]
[**@WebFreak001**](https://github.com/WebFreak001) commented on [26 jul. 2015 12:14 CEST](https://github.com/cakecatz/flex-toolbar/issues/41#issuecomment-124966985 "2015-07-26T10:14:56Z - Replied by Github Comment Enhancer"):
> [https://atom.io/packages/build](https://atom.io/packages/build) in this package for example you can define custom keybinds that are not assigned to a specific command

See https://github.com/noseglid/atom-build/blob/master/keymaps/build.json for the keymaps.

**Comment by WebFreak001** [comment]
No when creating a build script you can set `keymap` to something custom that will only trigger that one build file without selecting it from a dialog how you would with the other keybinds

**Comment by jerone** [comment]
You need to use the full command for your custom keystroke, see https://github.com/noseglid/atom-build/blob/9dd4cca2367a00ded0b82acd00e6628c260d9582/lib/build.js#L233

**Comment by WebFreak001** [comment]
Oh I didnt know that and I cant find any function to simulate keybinds in the atom documentation, so I guess this feature isn't needed

**Comment by jerone** [comment]
I don't think it's possible to define keystrokes with Atom API without attaching it to a command only.

**Comment by jerone** [comment]
I just confirmed on Atom Slack that shortcuts are always attached to commands. Closing this request.
