### ISSUE TITLE
Ability to add toolbar.cson to project root

### ISSUE THREAD

**Issue by WebFreak001** [cakecatz/flex-toolbar#42]
It would be nice to have project dependent toolbars when adding toolbar.cson to the projects root that just append/prepend to the regular toolbar.

**Comment by Moeriki** [comment]
+1 this!

**Comment by hoffmaan** [comment]
+1!

**Comment by malnvenshorn** [comment]
Would be nice to have an option to specify the path to the configuration file, because I would like to group all my config files for different plugins under ".atom/*.cson".

**Comment by UziTech** [comment]
@malnvenshorn this is possible in the settings

![image](https://user-images.githubusercontent.com/97994/34969914-d3f9e910-fa36-11e7-90ce-39f84e00bca9.png)

**Comment by malnvenshorn** [comment]
@UziTech Isn't this just the path to the 'main' config file which is per default in the config directory of atom? What I mean is the path of the "per project config".

**Comment by UziTech** [comment]
Oic, you want to be able to put the project config in a ".atom" folder in your project. 

At the moment I am pretty busy but if you wanted to submit a PR with a "Project Config Path" setting I would accept it.
