### ISSUE TITLE
Not recognizing .cson file

### ISSUE THREAD

**Issue by juanscv** [cakecatz/flex-toolbar#43]
The package isn't recognizing my toolbar.cson file and it's not showing any of my icons.
- When I save the file it says it was successfully updated.
- I've changed the location, the extension to .json, but nothing.

Atom 1.0.4 Windows 10 Pro Flex-Tool-bar 0.4.4

**Comment by jerone** [comment]
Are you sure your .cson / .json file is valid?

**Comment by juanscv** [comment]
I made the .cson out of the example.

**Comment by sethxd** [comment]
I'm having the same issue. Code and error look like:

![image](https://cloud.githubusercontent.com/assets/3084071/9612524/24f55928-50b4-11e5-9834-b31a169b1ba9.png)

![image](https://cloud.githubusercontent.com/assets/3084071/9612538/2ea7fe62-50b4-11e5-8af3-7c8ae0c39558.png)

**Comment by jerone** [comment]
> I'm having the same issue. Code and error look like:

If your toolbar is a file with json extension then you need to make your file valid. JSON requires the comma's at the end. CSON doesn't.

**Comment by sethxd** [comment]
Weird, it's definitely saved as 'toolbar.cson.' I tried saving as .json and adding commas, but that didn't work either.

**Comment by jerone** [comment]
Can you provide an exact copy of your toolbar file and note the tool-bar and flex-toolbar settings you've enabled. I can't confirm any issues with the example in the readme.

**Comment by sethxd** [comment]
Wow, nevermind. I'm an idiot and thought this was standalone, didn't realize it was a plugin for the main toolbar. Works great now!

**Comment by juanscv** [comment]
Quick update: Finally works, you can close this now.
