### ISSUE TITLE
Flex starts over tool-bar-main then moves below

### ISSUE THREAD

**Issue by juanscv** [cakecatz/flex-toolbar#44]
The flex-too-bar starts at the beginning of the toolbar then moves inexplicably to under tool-bar-main.

Atom 1.0.4 Windows 10 Pro Flex-Tool-bar 0.4.4

**Comment by jerone** [comment]
Can you post a screenshot.

**Comment by juanscv** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/955241/9186293/fd36852e-3f88-11e5-96d8-e64ae22ec60a.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/955241/9186294/fd3ce798-3f88-11e5-84b2-008cd5aff894.png)

**Comment by jerone** [comment]
I'm not sure I understand your problem. Maybe @cakecatz understand, or can you post clear steps to reproduce with all other packages disabled. I remember that the them you are using ([atom-metro-ui](https://atom.io/themes/metro-ui)) does some [styling of the tool-bar](https://github.com/Cirex/atom-metro-ui/blob/37cf57fa4934f5caca197a91c56ec66913dce651/styles/third-party/tool-bar.less) too.

**Comment by cakecatz** [comment]
Perhaps that cause is to not decided plugin loading order.

When changed grammar, `flex-tool-bar` will reload.
So if loading order is like below, 

1. `flex-tool-bar`
2. `tool-bar-main`
3. `flex-tool-bar`(changed grammar)

happens like this gif.

[![Gyazo](https://i.gyazo.com/e35c87eda9248ea704b483aca9388501.gif)](https://gyazo.com/e35c87eda9248ea704b483aca9388501)

**Comment by jerone** [comment]
What you could do is use the `priority` property.

**Comment by juanscv** [comment]
Yeah It happens like the .gif
What do I need to do for it to stay at the top?

**Comment by cakecatz** [comment]
@juanscv Like @jerone said, you could use `priority` property for it :smile: 
`priority` default value is `50`, so you need set lower value than it.

**Comment by jerone** [comment]
@cakecatz maybe you can set the default `priority` for flex-toolbar buttons & spacers to 45 (or something) to group buttons always together. With setting `priority` people can always override the default.
