### ISSUE TITLE
Lost focus when click on button

### ISSUE THREAD

**Issue by eMerzh** [cakecatz/flex-toolbar#45]
I was trying to add a button to callback editor:split-selections-into-lines

it seems that it work, butt i somewhat lost the focus on my code, so i'm unable to continue using the code pane unless i click on it (and loose my cursors)

is it the intended behavior? it there a way to fix it?

**Comment by cakecatz** [comment]
@eMerzh  That is not intended.
I'll fix it. Thanks :smile:

**Comment by cakecatz** [comment]
This is a tool-bar's issue.

**Comment by jerone** [comment]
This was fixed in Tool Bar v0.2.1
