### ISSUE TITLE
file bookmarks

### ISSUE THREAD

**Issue by ruicosta042** [cakecatz/flex-toolbar#47]
how can I add a file bookmark to the toolbar?
something like this?

```
    {
        type: "bookmark"
        url: "/home/myuser/TODO.txt"
    }
```

**Comment by ruicosta042** [comment]
I submitted a pull request with a solution for this: https://github.com/ruicosta042/flex-toolbar/pull/1

**Comment by jerone** [comment]
I think you should send a PR for this feature!

**Comment by UziTech** [comment]
I added this to the v1.0 release but I changed the syntax to use button.file instead of button.url
