### ISSUE TITLE
Add ability to stack icons

### ISSUE THREAD

**Issue by warrickhill** [cakecatz/flex-toolbar#49]
Like https://fortawesome.github.io/Font-Awesome/examples/#stacked would be nice

**Comment by cakecatz** [comment]
That is part of [tool-bar](https://github.com/suda/tool-bar/issues).
So please open issue at [tool-bar](https://github.com/suda/tool-bar/issues) repo :)

**Comment by jerone** [comment]
Does this work for more iconsets then FA?

**Comment by jerone** [comment]
Closing as this should be asked at the [Tool Bar](https://github.com/suda/tool-bar/) package.
