### ISSUE TITLE
how to show button for filename match certain pattern?

### ISSUE THREAD

**Issue by chenjau** [cakecatz/flex-toolbar#57]
hello, I'm making set of icons for rails development using flex-toolbar, but I can't figure it out how to match filename patterns. 
filenames for example:
foobar_spec.rb
foobar_controller.rb
foobar_helper.rb
I tried show: { pattern: "*_controller.rb" }, but doesn't work.

**Comment by UziTech** [comment]
@chenjau are you trying to only show the button when the open file name matches the pattern?

**Comment by chenjau** [comment]
Hi, yes, thats exactly what I want.

**Comment by UziTech** [comment]
this should be fixed in v0.13.1
