### ISSUE TITLE
Successfully updated message shows with every Atom startup. 

### ISSUE THREAD

**Issue by seanbuscay** [cakecatz/flex-toolbar#60]
After upgrading from v0.7.3 to v0.8.0 I started to get the following notification message every time I open Atom (via the command line or by application icon)

> The tool-bar was successfully updated.

@jerone Pointed me to the line of code which triggers the notification upon activate:

https://github.com/cakecatz/flex-toolbar/blob/master/lib/flex-tool-bar.coffee#L32

I am not sure if this is new desired behavior.  

If yes: Then I can change the line of code myself to prevent the minor annoyance.
If no: Then let me know if you need any further info from me to reproduce the issue.

I have tested and confirmed the message does not repeat each time in v0.7.3.

- I am on Mac OSX 10.11.3
- I am using tool-bar@0.3.0
- I am running Atom 1.5.4

**Comment by jerone** [comment]
Confirmed. I think it's a redundant notification when no actual change was done to the toolbar file.

Without testing, it looks like if we change the true on [this line](https://github.com/cakecatz/flex-toolbar/blob/master/lib/flex-tool-bar.coffee#L32) to false the notification shouldn't happen anymore.

@seanbuscay We're open for an PR.

**Comment by seanbuscay** [comment]
Actually it turns out to be line 98

https://github.com/cakecatz/flex-toolbar/blob/master/lib/flex-tool-bar.coffee#L98

I'll submit a pull request.

**Comment by seanbuscay** [comment]
@jerone In my testing, only line 98 causes the redundant notification every time.  

L88 defaults to false due to: `reloadToolbar: (withNotification=false)`
L32 appears to only trigger the message upon package activation.  Though it seems to not detect if there really was an update.

Do you agree?  I'll submit a change for just line 98 for now.

**Comment by jerone** [comment]
It looks like we need to toggle the `withNotification` argument on the following lines: 

* [L32](https://github.com/cakecatz/flex-toolbar/blob/master/lib/flex-tool-bar.coffee#L32) to remove notification on package activation.
* [L88](https://github.com/cakecatz/flex-toolbar/blob/master/lib/flex-tool-bar.coffee#L88) to show the notificaction when file _has_ changed.
* [L98](https://github.com/cakecatz/flex-toolbar/blob/master/lib/flex-tool-bar.coffee#L98) to remove notification on service connection.

**Comment by seanbuscay** [comment]
Ah, thanks.  I'll update my pull request.  

I'm going to send the true or false param each time, incase the reloadToolbar function signature every changes its default.  Plus it will show intent when called from each of the above lines.
