### ISSUE TITLE
toolbar.cson overwritten on launch

### ISSUE THREAD

**Issue by samuelam** [cakecatz/flex-toolbar#63]
As of 0.8.1 the toolbar.cson file is overwritten with the packaged version each time a new window is launched.

OS X 10.11.3
Atom 1.5.4
Toolbar 0.3.0

**Comment by jerone** [comment]
Can't confirm. Just to confirm, you have a file called `toolbar.cson` in your Atom root? And your "Tool Bar Configuration File Path" setting is empty?

**Comment by samuelam** [comment]
Clearing the configuration file path resolved the issue.
My path was set to `~/.atom/toolbar.cson`

**Comment by jerone** [comment]
Great to hear you've fixed it.
