### ISSUE TITLE
First user,and have a question

### ISSUE THREAD

**Issue by Javacym** [cakecatz/flex-toolbar#68]
about callback, i do not know where to find applications? who can tell me, like
`  {
    type: "button"
    icon: "file-text"
    callback: "application:new-file"
    tooltip: "Open New File"
    iconset:"fa"
  }`
where to find applications can use to.

**Comment by jerone** [comment]
You mean that you want to know where to find a list of commands? Please read this topic: https://discuss.atom.io/t/atom-methods/19826
