### ISSUE TITLE
Is there a way to select command?

### ISSUE THREAD

**Issue by Javacym** [cakecatz/flex-toolbar#69]
First,Thanks a lot for answer my question.
for example:
```cson
  {
    type: "button"
    icon: "columns"
    iconset: "fa"
    callback: "pane:split-right-and-copy-active-item"
    tooltip:"Pane to Right"
    style:{
        color:"#88CE8B"
    }
  }
```
this command is use to split left and copy-active item,I want press and hold Alt(or Ctrl, or Shift key) to change only split-left without copy-active-item.There is one way I know is create a new button,
is there another way?

**Comment by cakecatz** [comment]
@Javacym You can use callback with modifiers.

**Example Code**
```cson
{
  callback: 
    "": "pane:split-right-and-copy-active-item"
    "alt": "pane:split-left-and-copy-active-item"
}
```

**Available modifiers**: `alt`, `ctrl`, `shift` and combined modifiers `alt+ctrl`, etc.

**Comment by Javacym** [comment]
Thanks a lot, i works very nice.
