### ISSUE TITLE
Show/Hide toolbar buttons when image files are displayed

### ISSUE THREAD

**Issue by AshleyWright** [cakecatz/flex-toolbar#73]
I would like to be able to have buttons in the toolbar that only show when an image file of particular format is shown in the active pane (using image-view that comes packaged with atom).

I have discovered that this is not currently possible since there is no active editor and hence, from the toolbar's perspective, no path. Also `@currentGrammar` retains the value of the previous grammar.

Additionally, there is no suitable selector I could use to manually hide/show the toolbar button using my custom stylesheet.

**Comment by UziTech** [comment]
This is fixed in v0.13.2

You should be able to pattern match images based on their extension

```js
...
show: {
  pattern: "*.png"
}
...
```
