### ISSUE TITLE
Flex tool-bar with tool-bar set to full-width screws up tree-view sidebar scrolling

### ISSUE THREAD

**Issue by phoenixenero** [cakecatz/flex-toolbar#74]
Originally posted on:

<https://github.com/atom/tree-view/issues/844>
<https://github.com/suda/tool-bar/issues/146>

## Issue

Double clicking items in tree view is buggy when `flex-toolbar` package is enabled and tool-bar's setting is set to horizontal and full-width.

Issue does not appear when installing and enabling `suda/tool-bar-main` *while* flex-toolbar is enabled, or when `flex-toolbar` is disabled.

Here's a video showing the issue:
https://gfycat.com/AdeptWelcomeCoqui

Tool-bar is at the top of the video.

## Reproduction

1. install `flex-toolbar`
1. Add random stuff to `flex-toolbar` config
1. Disable all tool-bar community packages except `flex-toolbar`
1. Set `tool-bar` to horizontal full-width.
1. Open a project with tons of directories and files.
1. Scroll `tree-view` to the very bottom
1. Click or double-click a file in `tree-view`

## Workaround

Disable full-width tool-bar.

**Comment by cakecatz** [comment]
@phoenixenero Thanks for reporting.
I fixed this bug at version `0.10.1`.

**Comment by jerone** [comment]
Linking to commit https://github.com/cakecatz/flex-toolbar/commit/42d35de2f874e289edf00b5c01fecdbd6ec686a0

**Comment by jerone** [comment]
For future reference; this happens when switching file, all flex-tool-bar buttons are removed and then re-added depending on the grammar. Because removing all buttons (or just enough buttons to remove a row) the tool-bars height changes back and forth.
