### ISSUE TITLE
How to toggle package panes?

### ISSUE THREAD

**Issue by thomasfrobieter** [cakecatz/flex-toolbar#79]
Everything works fine, but i don´t get one thing to work ...

How do i toggle a pane, in my case the https://github.com/mrodalgaard/atom-todo-show pane.

Something like... 
`  {
    type: "button"
    url: "atom://packages/todo-show"
    callback: "todo-show"
    tooltip: "Todos"
    iconset: "ion"
    icon: "clipboard"
  }` ?

**Comment by thomasfrobieter** [comment]
**Got it!**

`  {
    type: "button"
    callback: "todo-show:find-in-workspace"
    tooltip: "Todos"
    iconset: "ion"
    icon: "clipboard"
  }`

The callback names are listed under settings > keybindings.

**Comment by jerone** [comment]
Great that you found the solution yourself.
