### ISSUE TITLE
Button event is living after update

### ISSUE THREAD

**Issue by cakecatz** [cakecatz/flex-toolbar#8]
`Edit toolbar` button open 2 tabs after update package.
Also, after disable and reenable.
![screen shot 2015-04-22 at 3 17 33 am](https://cloud.githubusercontent.com/assets/6136383/7259420/2af5a8f6-e89e-11e4-827f-94cb26766c33.png)

**Comment by jerone** [comment]
Maybe because the old and new events are now attached. Also reproducible after restart or refresh?

**Comment by cakecatz** [comment]
@jerone I was thinking the same thing.
But the cause was command is not disposed.
So I have fixed this.
