### ISSUE TITLE
Define default values?

### ISSUE THREAD

**Issue by idleberg** [cakecatz/flex-toolbar#83]
I just came across this plugin and was wondering: is it only possible to hide elements in the toolbar via `toolbar.cson`? I'd find it more useful, if I could set the defaults in my `tool-bar` code and overwrite them, if desired, in `toolbar.cson`.

For example, I'd like to hide buttons unless I'm working in a certain scope:

``` coffeescript
@toolBar.addButton
    icon: 'paper-plane'
    callback: 'makensis:compile'
    tooltip: "Compile NSIS"
    iconset: 'fa'
    hide: '!nsis'
```

If I understand this plugin correctly, I would have to ask the user to edit `toolbar.cson` or edit it in JavaScript.

**Comment by jerone** [comment]
Within Flex Toolbar it's only possible to [hide/enable buttons depending on different grammars](https://github.com/cakecatz/flex-toolbar#hideshow-disableenable-button).

**Comment by idleberg** [comment]
I understood that, I'm just surprised it's not possible to use `hide/show` or `disable/enable` in my `consumeToolBar()` function in which I populate my toolbar.

Take my own toolbar as an example. It is only useful when working in specific grammar. I was hoping, I could simply use a [package dependence](https://github.com/steelbrain/package-deps) for `flex-toolbar` and use the `disable` option provided by it in my `consumeToolBar()` function. Instead, I either have to use `fs.readFile` to modify `toolbar.cson` or ask the user to do so.

While I embrace the features `flex-toolbar` provides, I don't understand its purpose when it relies on user interaction. I'd find it far more useful, if I could use its features when populating a toolbar and _optionally_ overwrite these settings in `toolbar.cson`.

**Comment by jerone** [comment]
Flex Tool Bar is just a plugin for the Tool Bar package. It's not designed to be used as a dependency of any other package. You could try to find the `toolbar.cson` file from within your package, but that's highly experimental. But even then, you don't have access to your added button.

This looks like more a question for Tool Bar package. What you can try is using the (unofficial) [return value](https://github.com/suda/tool-bar/blob/master/lib/tool-bar-manager.js#L20) of `addButton` and hide/show the button on your own.

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.
