### ISSUE TITLE
multiple command callback

### ISSUE THREAD

**Issue by cakecatz** [cakecatz/flex-toolbar#9]
I want to attach multiple command to callback.
It is roughly like this.

    "callback" : "editor:select-line,core:copy"

This callback is copying line.

**Comment by jerone** [comment]
I couldn't find any rules that specify which characters are allowed as single commands. Maybe a `,` or e.g. `;` is also allowed as part of the commando.

Besides, are commands sync or async?

**Comment by cakecatz** [comment]
@jerone Then,I'll use JSON's array :smile_cat: 

    "callback" : ["editor:select-line", "core:copy"]

And, I'm assuming sync process.

**Comment by cakecatz** [comment]
"callback" : ["pane:split-right", "pane:split-right"]

![split-pane](http://i.gyazo.com/fd80966abac6bba17729c452ab6c243f.gif)

**Comment by jerone** [comment]
[**@cakecatz**](https://github.com/cakecatz) commented on [23 apr. 2015 19:44 CEST](https://github.com/cakecatz/flex-toolbar/issues/9#issuecomment-95667516 "2015-04-23T17:44:02Z - Replied by Github Comment Enhancer"):
>     "callback" : ["editor:select-line", "core:copy"]
> 
> And, I'm assuming sync process.

With async vs sync I mean that copy maybe executed before editor is finished selecting a line.

Great feature btw.

**Comment by cakecatz** [comment]
> With async vs sync I mean that copy maybe executed before editor is finished selecting a line.

Ah, It's no problem.
I'm using `atom.commands.dispatch` and it's probably synchronous process.

**Comment by jerone** [comment]
[According to the docs](https://atom.io/docs/api/latest/CommandRegistry), all event handlers are fired synchronously and in order of binding. With the exception of `setTimeout` functions, this will probably be OK for all situations.

**Comment by cakecatz** [comment]
:smile:

**Comment by jerone** [comment]
This has been fixed in https://github.com/cakecatz/flex-toolbar/commit/b8b1918fc03134a96ddfbf39124fbf3b0482e9e7
