### ISSUE TITLE
Feature Request - Add classes to icons

### ISSUE THREAD

**Issue by blizzardengle** [cakecatz/flex-toolbar#93]
**What I've Done So Far**<br>
So I hacked my `flex-tool-bar.coffee` file and added the following code in the `addButtons` method:

```
if btn.addClass?
    classes = btn.addClass.split ' '
    for aClass in classes
        button.element.classList.add aClass.trim()
```

I put the above code in the addButtons method like so:

```
button.element.classList.add "tool-bar-mode-#{btn.mode}" if btn.mode

    [ My new code here ]

if btn.style?
     for propName, v of btn.style
         button.element.style[changeCase.camelCase(propName)] = v
```

**The Actual Feature Request(s)**<br>

Would you be willing to add this into your package in the next release?

**Example That Works**<br>
```
{
    type: "button"
    icon: "columns"
    addClass: "fa-rotate-270"
    iconset: "fa"
    callback: ["pane:split-down"]
}
```

Or you could do something like this; excepts this fa rules overweight each other so only one still shows but you get the point.

```
{
    type: "button"
    icon: "columns"
    addClass: "fa-rotate-270 fa-flip-horizontal"
    iconset: "fa"
    callback: ["pane:split-down"]
}
```

**Comment by UziTech** [comment]
@blizzardengle if you submit a pull request I could merge it

**Comment by blizzardengle** [comment]
I actually already submitted a pull request for this a long time ago and it was accepted. If you look through the README.MD for the repo this feature is already in there. Thanks for following up though.
