### ISSUE TITLE
Every time atom restarts; it overwrites my existing toolbar.cson file. 

### ISSUE THREAD

**Issue by malaysarkar** [cakecatz/flex-toolbar#94]
If I try to some value in "Toolbar Configuration File Path" then every time I close and open atom. 
It replaces my existing ~/.atom/toolbar.cson with a new file and prompts about it too.
So there are three issues here:
1. it simply overwrites ~/.atom/toolbar.cson even if there  is  a valid file there.
2. it is not loading the project level toolbar.cson after I tinkered with it's value
3. There is no way to revert it back to original; setting if empty value did stop replacing my existing ~/.atom/toolbar.cson but it is still not loading my project toolbar.cson

**Comment by ethernal** [comment]
I can confirm but It reverted back - I disabled reload and removed the custom file name. Then enabled reload and did not add custom file. It works but seems like a default name bug.

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.
