### ISSUE TITLE
Allow tooltip as an object

### ISSUE THREAD

**Issue by danielbayley** [cakecatz/flex-toolbar#96]
It would be cool if you could pass `tooltip:` as an `{object}` as documented [here] and [here][2] … something like:
~~~ cson
type: 'button'
  icon: 'octicon'
  callback: 'some-package:command'
  tooltip:
    title: "Tooltip <kbd>⌘?</kbd>"
    #keyBindingCommand: '' # This would actually just be a duplicate value of `callback:`
    html: true
~~~
The particular idea here obviously being to display a little <kbd>⌘K</kbd>eybinding reminder in the tooltip.

[here]: https://atom.io/docs/api/v0.199.0/TooltipManager#instance-add
[2]: http://getbootstrap.com/javascript/#tooltips-options

**Comment by UziTech** [comment]
A PR has been submitted to the tool-bar package https://github.com/suda/tool-bar/pull/216

**Comment by UziTech** [comment]
This should work with [toolbar v1.1.5](https://github.com/suda/tool-bar/blob/master/CHANGELOG.md)
