### ISSUE TITLE
Show Only For Git Repos?

### ISSUE THREAD

**Issue by dodekeract** [cakecatz/flex-toolbar#99]
Is there a way to do that currently? I'd like to add a button to go to the issues into my toolbar, but logically it should only show if I'm in a git repo.

Otherwise consider this a feature request.

**Comment by akhilcb** [comment]
+1

**Comment by dodekeract** [comment]
@NanerLee @akhilcb Instead of spamming people's mail inboxes just use GitHub's :+1: feature please and leave this kind of feedback in the original issue comment. Thanks.

**Comment by UziTech** [comment]
You could use a project specific configuration and only show the button in certain projects.

You could also use a `.coffee` or `.js` file and use some logic to add a button to the exports if it is in a git repo

**Comment by UziTech** [comment]
I'm going to close this as stale.

If this is still an issue feel free to let us know.
